language: csharp

jobs:
  include:
    - name: '[ubuntu xenial] Support for .NET Core 1.0 to 2.2'
      os: linux
      dist: xenial
      mono: none
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo apt-get update
        - sudo apt-get install apt-transport-https dotnet-dev-1.1.8 dotnet-sdk-2.1 dotnet-sdk-2.2

        - dotnet new -i ./Content
        - dotnet --info

        - dotnet new nunit -n CSharpNetCore1   --framework netcoreapp1.0 -lang c#; dotnet test CSharpNetCore1;
        - dotnet new nunit -n FSharpNetCore1   --framework netcoreapp1.0 -lang f#; dotnet test FSharpNetCore1;
        - dotnet new nunit -n VBasicNetCore1   --framework netcoreapp1.0 -lang vb; dotnet test VBasicNetCore1;

        - dotnet new nunit -n CSharpNetCore11  --framework netcoreapp1.1 -lang c#; dotnet test CSharpNetCore11;
        - dotnet new nunit -n FSharpNetCore11  --framework netcoreapp1.1 -lang f#; dotnet test FSharpNetCore11;
        - dotnet new nunit -n VBasicNetCore11  --framework netcoreapp1.1 -lang vb; dotnet test VBasicNetCore11;

        - dotnet new nunit -n CSharpNetCore2   --framework netcoreapp2.0 -lang c#; dotnet test CSharpNetCore2;
        - dotnet new nunit -n FSharpNetCore2   --framework netcoreapp2.0 -lang f#; dotnet test FSharpNetCore2;
        - dotnet new nunit -n VBasicNetCore2   --framework netcoreapp2.0 -lang vb; dotnet test VBasicNetCore2;

        - dotnet new nunit -n CSharpNetCore21  --framework netcoreapp2.1 -lang c#;
        - dotnet new nunit-test -n NewTestFixture -o CSharpNetCore21 -lang c#;
        - dotnet test CSharpNetCore21;
        - dotnet new nunit -n FSharpNetCore21  --framework netcoreapp2.1 -lang f#;
        - dotnet new nunit-test -n NewTestFixture -o FSharpNetCore21 -lang f#;
        - dotnet test FSharpNetCore21;
        - dotnet new nunit -n VBasicNetCore21  --framework netcoreapp2.1 -lang vb;
        - dotnet new nunit-test -n NewTestFixture -o VBasicNetCore21 -lang vb;
        - dotnet test VBasicNetCore21;

        - dotnet new nunit -n CSharpNetCore22   --framework netcoreapp2.2 -lang c#; dotnet test CSharpNetCore22
        - dotnet new nunit -n FSharpNetCore22   --framework netcoreapp2.2 -lang f#; dotnet test FSharpNetCore22
        - dotnet new nunit -n VBasicNetCore22   --framework netcoreapp2.2 -lang vb; dotnet test VBasicNetCore22

    - name: '[ubuntu bionic] Support for .NET Core 3.0 to 3.1'
      os: linux
      dist: bionic
      mono: none
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo apt-get update
        - sudo apt-get install apt-transport-https dotnet-sdk-3.0 dotnet-sdk-3.1

        - dotnet new -i ./Content
        - dotnet --info

        - dotnet new nunit -n CSharpNetCore30   --framework netcoreapp3.0 -lang c#; dotnet test CSharpNetCore30
        - dotnet new nunit -n FSharpNetCore30   --framework netcoreapp3.0 -lang f#; dotnet test FSharpNetCore30
        - dotnet new nunit -n VBasicNetCore30   --framework netcoreapp3.0 -lang vb; dotnet test VBasicNetCore30

        - dotnet new nunit -n CSharpNetCore31   --framework netcoreapp3.1 -lang c#; dotnet test CSharpNetCore31
        - dotnet new nunit -n FSharpNetCore31   --framework netcoreapp3.1 -lang f#; dotnet test FSharpNetCore31
        - dotnet new nunit -n VBasicNetCore31   --framework netcoreapp3.1 -lang vb; dotnet test VBasicNetCore31

    - name: '[ubuntu bionic] Support for .NET 5.0'
      os: linux
      dist: bionic
      mono: none
      script:
        - "curl -H 'Cache-Control: no-cache' -L https://aka.ms/install-dotnet-preview -o install-dotnet-preview.sh"
        - sudo bash install-dotnet-preview.sh

        - dotnet new -i ./Content
        - dotnet --info

        - dotnet new nunit -n CSharpNetCore50   --framework net5.0 -lang c#; dotnet test CSharpNetCore50
        - dotnet new nunit -n FSharpNetCore50   --framework net5.0 -lang f#; dotnet test FSharpNetCore50
        - dotnet new nunit -n VBasicNetCore50   --framework net5.0 -lang vb; dotnet test VBasicNetCore50

    - name: '[ubuntu bionic] Support for Mono'
      os: linux
      dist: bionic
      mono: latest
      script:
        - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo apt-get update
        - sudo apt-get install apt-transport-https dotnet-sdk-3.1

        # specify FrameworkPathOverride to run tests under Mono
        - export FrameworkPathOverride=/usr/lib/mono/4.7-api

        # unfortunately, F# under full .NET Framework issues a compilation error, the issue is in F# compiler, disable tests for now
        # unfortunately, Mono under Mac OSX could not resolve .NET Framework assemblies and issues many errors, disable tests for now
        - dotnet new nunit -n CSharpNet35  --framework net35 -lang c#; dotnet test CSharpNet35
        - dotnet new nunit -n VBasicNet35  --framework net35 -lang vb; dotnet test VBasicNet35

        - dotnet new nunit -n CSharpNet40  --framework net40 -lang c#; dotnet test CSharpNet40
        - dotnet new nunit -n VBasicNet40  --framework net40 -lang vb; dotnet test VBasicNet40

        - dotnet new nunit -n CSharpNet45  --framework net45 -lang c#; dotnet test CSharpNet45
        - dotnet new nunit -n VBasicNet45  --framework net45 -lang vb; dotnet test VBasicNet45

        - dotnet new nunit -n CSharpNet451 --framework net451 -lang c#; dotnet test CSharpNet451
        - dotnet new nunit -n VBasicNet451 --framework net451 -lang vb; dotnet test VBasicNet451

        - dotnet new nunit -n CSharpNet452 --framework net452 -lang c#; dotnet test CSharpNet452
        - dotnet new nunit -n VBasicNet452 --framework net452 -lang vb; dotnet test VBasicNet452

        - dotnet new nunit -n CSharpNet46  --framework net46 -lang c#; dotnet test CSharpNet46
        - dotnet new nunit -n VBasicNet46  --framework net46 -lang vb; dotnet test VBasicNet46

        - dotnet new nunit -n CSharpNet461 --framework net461 -lang c#; dotnet test CSharpNet461
        - dotnet new nunit -n VBasicNet461 --framework net461 -lang vb; dotnet test VBasicNet461

        - dotnet new nunit -n CSharpNet462 --framework net462 -lang c#; dotnet test CSharpNet462
        - dotnet new nunit -n VBasicNet462 --framework net462 -lang vb; dotnet test VBasicNet462

        - dotnet new nunit -n CSharpNet47 --framework net47 -lang c#; dotnet test CSharpNet47
        - dotnet new nunit -n VBasicNet47 --framework net47 -lang vb; dotnet test VBasicNet47

        - dotnet new nunit -n CSharpNet471 --framework net471 -lang c#; dotnet test CSharpNet471
        - dotnet new nunit -n VBasicNet471 --framework net471 -lang vb; dotnet test VBasicNet471

        - dotnet new nunit -n CSharpNet472 --framework net472 -lang c#; dotnet test CSharpNet472
        - dotnet new nunit -n VBasicNet472 --framework net472 -lang vb; dotnet test VBasicNet472

        # uncomment when mono will support net48
        #- dotnet new nunit -n CSharpNet48 --framework net48 -lang c#; dotnet test CSharpNet48
        #- dotnet new nunit -n VBasicNet48 --framework net48 -lang vb; dotnet test VBasicNet48

    - name: '[OSX] Support for .NET Core 1.0 to 2.2'
      os: osx
      osx_image: xcode11.2
      mono: none
      script:
        - wget --retry-connrefused --waitretry=1 -O /tmp/dotnet-dev-osx-x64.1.1.8.pkg https://download.microsoft.com/download/6/5/F/65F1653E-F835-4DE3-BB36-F324D3925F32/dotnet-dev-osx-x64.1.1.8.pkg
        - wget --retry-connrefused --waitretry=1 -O /tmp/dotnet-sdk-2.1.505-osx-x64.pkg https://download.visualstudio.microsoft.com/download/pr/7908138c-c0cf-4e5a-b28a-66cf7a781808/a36fe63192ee49593890d84b23729292/dotnet-sdk-2.1.505-osx-x64.pkg
        - wget --retry-connrefused --waitretry=1 -O /tmp/dotnet-sdk-2.2.105-osx-x64.pkg https://download.visualstudio.microsoft.com/download/pr/4850aa8f-44a9-4c4a-9961-f18aa4d90ceb/07d790444f3ba6b412a76d6f1aced338/dotnet-sdk-2.2.105-osx-x64.pkg
        - sudo installer -pkg /tmp/dotnet-dev-osx-x64.1.1.8.pkg -target /
        - sudo installer -pkg /tmp/dotnet-sdk-2.1.505-osx-x64.pkg -target /
        - sudo installer -pkg /tmp/dotnet-sdk-2.2.105-osx-x64.pkg -target /
        - ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/

        - dotnet new -i ./Content
        - dotnet --info

        - dotnet new nunit -n CSharpNetCore1   --framework netcoreapp1.0 -lang c#; dotnet test CSharpNetCore1;
        - dotnet new nunit -n FSharpNetCore1   --framework netcoreapp1.0 -lang f#; dotnet test FSharpNetCore1;
        - dotnet new nunit -n VBasicNetCore1   --framework netcoreapp1.0 -lang vb; dotnet test VBasicNetCore1;

        - dotnet new nunit -n CSharpNetCore11  --framework netcoreapp1.1 -lang c#; dotnet test CSharpNetCore11;
        - dotnet new nunit -n FSharpNetCore11  --framework netcoreapp1.1 -lang f#; dotnet test FSharpNetCore11;
        - dotnet new nunit -n VBasicNetCore11  --framework netcoreapp1.1 -lang vb; dotnet test VBasicNetCore11;

        - dotnet new nunit -n CSharpNetCore2   --framework netcoreapp2.0 -lang c#; dotnet test CSharpNetCore2;
        - dotnet new nunit -n FSharpNetCore2   --framework netcoreapp2.0 -lang f#; dotnet test FSharpNetCore2;
        - dotnet new nunit -n VBasicNetCore2   --framework netcoreapp2.0 -lang vb; dotnet test VBasicNetCore2;

        - dotnet new nunit -n CSharpNetCore21  --framework netcoreapp2.1 -lang c#;
        - dotnet new nunit-test -n NewTestFixture -o CSharpNetCore21 -lang c#;
        - dotnet test CSharpNetCore21;
        - dotnet new nunit -n FSharpNetCore21  --framework netcoreapp2.1 -lang f#;
        - dotnet new nunit-test -n NewTestFixture -o FSharpNetCore21 -lang f#;
        - dotnet test FSharpNetCore21;
        - dotnet new nunit -n VBasicNetCore21  --framework netcoreapp2.1 -lang vb;
        - dotnet new nunit-test -n NewTestFixture -o VBasicNetCore21 -lang vb;
        - dotnet test VBasicNetCore21;

        - dotnet new nunit -n CSharpNetCore22   --framework netcoreapp2.2 -lang c#; dotnet test CSharpNetCore22
        - dotnet new nunit -n FSharpNetCore22   --framework netcoreapp2.2 -lang f#; dotnet test FSharpNetCore22
        - dotnet new nunit -n VBasicNetCore22   --framework netcoreapp2.2 -lang vb; dotnet test VBasicNetCore22

    - name: '[OSX] Support for .NET Core 3.0 to 3.1'
      os: osx
      osx_image: xcode11.2
      mono: none
      script:
        - wget --retry-connrefused --waitretry=1 -O /tmp/dotnet-sdk-3.0.100-osx-x64.pkg https://download.visualstudio.microsoft.com/download/pr/5c281f95-91c4-499d-baa2-31fec919047a/38c6964d72438ac30032bce516b655d9/dotnet-sdk-3.0.100-osx-x64.pkg
        - wget --retry-connrefused --waitretry=1 -O /tmp/dotnet-sdk-3.1.201-osx-x64.pkg https://download.visualstudio.microsoft.com/download/pr/905598d0-17a3-4b42-bf13-c5a69d7aac87/853aff73920dcb013c09a74f05da7f6a/dotnet-sdk-3.1.201-osx-x64.pkg
        - sudo installer -pkg /tmp/dotnet-sdk-3.0.100-osx-x64.pkg -target /
        - sudo installer -pkg /tmp/dotnet-sdk-3.1.201-osx-x64.pkg -target /
        - ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/

        - dotnet new -i ./Content
        - dotnet --info

        - dotnet new nunit -n CSharpNetCore30   --framework netcoreapp3.0 -lang c#; dotnet test CSharpNetCore30
        - dotnet new nunit -n FSharpNetCore30   --framework netcoreapp3.0 -lang f#; dotnet test FSharpNetCore30
        - dotnet new nunit -n VBasicNetCore30   --framework netcoreapp3.0 -lang vb; dotnet test VBasicNetCore30

        - dotnet new nunit -n CSharpNetCore31   --framework netcoreapp3.1 -lang c#; dotnet test CSharpNetCore31
        - dotnet new nunit -n FSharpNetCore31   --framework netcoreapp3.1 -lang f#; dotnet test FSharpNetCore31
        - dotnet new nunit -n VBasicNetCore31   --framework netcoreapp3.1 -lang vb; dotnet test VBasicNetCore31

    - name: '[OSX] Support for .NET 5.0'
      os: osx
      osx_image: xcode11.2
      mono: none
      script:
        - wget --retry-connrefused --waitretry=1 -O /tmp/dotnet-sdk-5.0.100-osx-x64.pkg https://download.visualstudio.microsoft.com/download/pr/3ce4af4f-f5d5-406c-a065-2ecc9bcc5fd2/353affd22a0727b476998312738ac35f/dotnet-sdk-5.0.100-preview.2.20176.6-osx-x64.pkg
        - sudo installer -pkg /tmp/dotnet-sdk-5.0.100-osx-x64.pkg -target /
        - ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/

        - dotnet new -i ./Content
        - dotnet --info

        - dotnet new nunit -n CSharpNetCore50   --framework net5.0 -lang c#; dotnet test CSharpNetCore50
        - dotnet new nunit -n FSharpNetCore50   --framework net5.0 -lang f#; dotnet test FSharpNetCore50
        - dotnet new nunit -n VBasicNetCore50   --framework net5.0 -lang vb; dotnet test VBasicNetCore50
